version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_DRIVER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - dbdata:/var/lib/Vad_postgresql/data
volumes:
  dbdata: